version: '3'
services:
  kouifapi:
    build: .
    ports:
     - "5000:80"
    volumes:
      - /container/ko-uif-api:/app/resource
    networks:
      application:
        ipv4_address: 10.0.0.10
networks:
  application:
    external:
      name: application